### ISSUE TITLE
How to find file?

### ISSUE THREAD

**Issue by LanShanPi** [facebookresearch/RLCD#3]
In this command "python alpaca_farm/pretrained_models/convert_llama7b_to_alpacafarm_format.py --in-dir {path/to/huggingface/format/llama7b} --out-dir alpaca_farm/pretrained_models", where the "convert_llama7b_to_alpacafarm_format.py", I have clone the code  (https://github.com/tatsu-lab/alpaca_farm), but in "alpaca_farm/pretrained_models" only one file: recover_model_weights.py and I have not find the convert_llama7b_to_alpacafarm_format.py . Can you give me some tips.

**Comment by yangkevin2** [comment]
Hi, 

Please see the instructions at the top of our README for setting up alpaca_farm. We're using a modified version of alpaca_farm, which can be obtained by checking out the corresponding version of alpaca_farm and then applying our patch. The "convert_llama7b_to_alpacafarm_format.py" is supplied in our patch file.

**Comment by LanShanPi** [comment]
ok,Thanks!
