### ISSUE TITLE
Missing requirements.txt File

### ISSUE THREAD

**Issue by ren258** [facebookresearch/RLCD#6]
I’m trying to get it up and running, but I noticed there isn’t a requirements.txt file in the repo. It would be super helpful to have one so that everyone knows exactly which Python packages are needed to get things working smoothly.

Appreciate your work on this!

**Comment by yangkevin2** [comment]
Hi, thanks for your interest!

There shouldn't be any real requirements beyond what's in the alpaca_farm repo already - once you have that pointed to the correct commit and have it installed and working following their instructions, this repo should basically just work.

**Comment by ren258** [comment]
Thank you so much!
